version: '3.8'
services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    restart: always
  frontend:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
